# Theoretical Questions:


## 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

**ANSWER:**

> NumPy is a popular Python library that makes working with numbers, especially large sets of numbers, much easier and faster. It's widely used in fields like scientific computing and data analysis. Here's why it's so useful:

# Purpose of NumPy

1. **Handling Big Data Sets**: NumPy lets you work with large collections of numbers efficiently. It uses a special kind of array called 'ndarray' that can hold data in a structured way, much more efficiently than standard Python lists.

2. **Math Tools**: It comes with a lot of built-in tools for doing math, like finding the average, doing algebra, and even working with random numbers. This means you can perform complex calculations quickly and easily.

3. **Data Analysis**: NumPy is great for cleaning and organizing data, which is a big part of data analysis. It works well with other data-focused libraries like pandas, making it a key tool for anyone analyzing data.

4. **Works Well with Others**: NumPy integrates smoothly with other Python libraries, which means you can easily combine it with other tools for scientific computing, plotting, or machine learning.

# Advantages of NumPy

1. **Speed**: NumPy is much faster than standard Python for numerical tasks because it's written in C and uses efficient techniques to handle data. This means tasks that might take minutes with regular Python lists can be done in seconds with NumPy arrays.

2. **Less Memory Use**: NumPy arrays are more memory-efficient than Python lists. This means you can work with bigger data sets without using up all your computer's memory.

3. **Lots of Features**: It offers a wide range of functions, from basic math to complex statistical operations, all optimized for performance.

4. **User-Friendly**: The library is designed to be easy to use. You can quickly perform operations on entire arrays of data, which simplifies the code and reduces errors.

5. **Strong Community**: NumPy has a large community of users and developers, providing plenty of resources, tutorials, and support. It also means it works well with a lot of other tools and libraries.

# Enhancing Python

By itself, Python isn't optimized for handling large-scale numerical data. NumPy fills this gap by providing:

1. **Fast Computations**: It speeds up the process of working with large data sets.
2. **Clean Code**: You can do more with less code, making it easier to read and maintain.
3. **Consistent Tools**: It offers a reliable set of functions and tools for working with numbers, so you don’t have to reinvent the wheel.

##2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Both 'np.mean()' and 'np.average()' in NumPy are used to calculate the average of a set of numbers, but they have some differences:

# 'np.mean()'
- **Purpose**: It calculates the simple average (mean) of all the numbers in the array.
- **How it works**: Adds up all the numbers and then divides by the total count of numbers.
- **Usage**: Use 'np.mean()' when you just want the straightforward average without considering any weights.

# 'np.average()'
- **Purpose**: It can calculate a weighted average, which means you can give different importance (weights) to different numbers.
- **How it works**: If you provide weights, it multiplies each number by its weight, adds those results together, and then divides by the total of the weights.
- **Usage**: Use 'np.average()' when you have weights and want to calculate a weighted average, where some numbers are more important than others.

# When to Use Each
- Use **'np.mean()'** for a regular average when all numbers should be treated equally.
- Use **'np.average()'** when some numbers should count more than others, like when averaging test scores where some tests are more important.

##3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In [ ]:
We can use slicing or the 'np.flip()' function.

# 1D Array

#For a one-dimensional array, you can reverse the elements using slicing:


import numpy as np

# 1D array example
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]

print(reversed_arr_1d)  # Output: [5 4 3 2 1]


# 2D Array

#For a two-dimensional array, you can reverse the array along different axes:

# 1.Reverse all rows (along the vertical axis, or axis 0):


# 2D array example
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_arr_rows = arr_2d[::-1, :]

print(reversed_arr_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]


# 2.Reverse all columns (along the horizontal axis, or axis 1):


reversed_arr_columns = arr_2d[:, ::-1]

print(reversed_arr_columns)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]


# 3.Reverse both axes (both rows and columns):


reversed_arr_both = arr_2d[::-1, ::-1]

print(reversed_arr_both)
# Output:
# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]


# Using 'np.flip()'

# 'np.flip()' can also reverse arrays along specified axes:

- Reverse a 1D array:


reversed_arr_1d_flip = np.flip(arr_1d)

print(reversed_arr_1d_flip)  # Output: [5 4 3 2 1]


# - Reverse a 2D array along different axes:


# Reverse all rows
reversed_arr_rows_flip = np.flip(arr_2d, axis=0)
print(reversed_arr_rows_flip)

# Reverse all columns
reversed_arr_columns_flip = np.flip(arr_2d, axis=1)
print(reversed_arr_columns_flip)

##4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

In [ ]:
# Determining Data Type

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

data_type = arr.dtype

print(data_type)

# Importance of Data Types
'''
1.Memory Management:
   - Using the appropriate data type helps save memory, which is crucial when working with large datasets.

2.Performance:
   - Data types affect computational speed. Operations on smaller data types can be faster and use less memory bandwidth. However, using a smaller data type might reduce precision, so it's a balance between speed and accuracy.

3.Compatibility:
   - Ensuring the correct data type is important for compatibility with other libraries and functions that might expect specific types.
'''

##5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

### What is an 'ndarray' in NumPy?

An 'ndarray' (short for "n-dimensional array") is a central data structure in NumPy. It’s a type of array that can hold numbers and can be multi-dimensional (like 1D, 2D, or even 3D).

### Key Features of 'ndarray'

1. **Fixed Size**: Once you create an 'ndarray', its size doesn’t change. You can't add or remove elements.

2. **Efficient**: 'ndarray' is very fast for numerical operations because it’s implemented in C and can do many operations at once.

3. **Homogeneous**: All elements in an 'ndarray' must be of the same type (like all integers or all floats).

4. **Multi-dimensional**: It can be one-dimensional (like a list), two-dimensional (like a matrix), or more. This allows for more complex data structures.

5. **Vectorized Operations**: You can perform operations on all elements at once without writing loops, which makes the code cleaner and faster.

6. **Broadcasting**: This feature allows you to perform arithmetic operations on arrays of different sizes and shapes in a smart way.

### How 'ndarray' Differs from Python Lists

1. **Speed**: 'ndarray' is faster for numerical tasks because it’s optimized for performance. Python lists can be slower for these operations.

2. **Fixed Size**: 'ndarray' size is fixed after creation, while Python lists can grow or shrink.

3. **Homogeneity**: All elements in an 'ndarray' must be of the same type, but Python lists can hold mixed types (e.g., integers, strings).

4. **Multi-dimensional**: 'ndarray' can be multi-dimensional (e.g., 2D matrices), while Python lists are typically one-dimensional, although you can nest lists to mimic dimensions.

5. **Operations**: 'ndarray' supports vectorized operations, meaning you can do calculations on entire arrays quickly, while Python lists require manual loops for similar operations.

##6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.


NumPy arrays are better than Python lists for large numerical operations because they are:

1. **Faster**: Implemented in C and support vectorized operations, so they handle numbers quickly.
2. **Memory Efficient**: Use less memory because they store elements in a compact, fixed data type.
3. **Convenient**: Have built-in, optimized functions for many operations, avoiding the need for loops.

##7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

In [ ]:
# vstack()
# - Stacks arrays vertically (row-wise).
# - Example:

  arr1 = np.array([1, 2, 3])
  arr2 = np.array([4, 5, 6])
  result = np.vstack((arr1, arr2))
  print(result)  # [[1 2 3]
                #  [4 5 6]]


# hstack()
# - Stacks arrays horizontally (column-wise).
# - Example:

  arr1 = np.array([1, 2, 3])
  arr2 = np.array([4, 5, 6])
  result = np.hstack((arr1, arr2))
  print(result)  # [1 2 3 4 5 6]

##8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

In [ ]:
# 'fliplr()'

# - Purpose: Flips an array left to right (horizontally).
# - Effect: Reverses the order of columns.
# - Usage: Works on 2D arrays or higher.
# - Example:

  import numpy as np

  arr = np.array([[1, 2, 3],
                  [4, 5, 6]])
  result = np.fliplr(arr)
  print(result)
  # Output:
  # [[3 2 1]
  #  [6 5 4]]

# 'flipud()'

# - Purpose: Flips an array upside down (vertically).
# - Effect: Reverses the order of rows.
# - Usage: Works on 2D arrays or higher.
# - Example:

  arr = np.array([[1, 2, 3],
                  [4, 5, 6]])
  result = np.flipud(arr)
  print(result)
  # Output:
  # [[4 5 6]
  #  [1 2 3]]

##9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [ ]:
# The array_split() method in NumPy is used to split an array into multiple sub-arrays. It is similar to split(), but it can handle cases where the array does not split evenly.

# Functionality of array_split()

# - Purpose: To divide an array into a specified number of sub-arrays.
# - Parameters:
#   1. ary: The array to be split.
#   2. indices_or_sections: Can be an integer (number of equal-sized splits) or a list of indices (defining where the splits should occur).

# Handling Uneven Splits

# When the array cannot be evenly split, array_split() handles the remainder by creating sub-arrays of different sizes. The first few sub-arrays will have one more element than the rest.

# Example:


import numpy as np

arr = np.array([1, 2, 3, 4, 5])
split_arr = np.array_split(arr, 3)

for sub_arr in split_arr:
    print(sub_arr)


# # Output:

# # [1 2]
# # [3 4]
# [5]


# In this example, the original array has 5 elements and is split into 3 parts. The first two sub-arrays have 2 elements each, and the last one has 1 element. This is how array_split() manages uneven splits, ensuring that each sub-array gets as close to equal elements as possible.

##10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In [ ]:
# Vectorization

# Concept: Vectorization in NumPy means performing operations on entire arrays at once, instead of looping through elements one by one.

# Benefits:
# - Speed: Vectorized operations are faster because they use low-level optimized C code.
# - Simpler Code: You can write cleaner and more readable code without explicit loops.

# Example:
import numpy as np

arr = np.array([1, 2, 3, 4])
result = arr * 2  # Multiply all elements by 2
print(result)  # Output: [2 4 6 8]

# Here, arr * 2 multiplies each element in arr by 2, without needing a loop.

# Broadcasting

# Concept: Broadcasting allows NumPy to perform operations on arrays of different shapes by "stretching" the smaller array to match the shape of the larger one.

# Benefits:
# - Memory Efficiency: No need to create multiple copies of the data.
# - Flexibility: You can perform operations on arrays of different sizes without resizing them.

# Example:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])

result = arr1 + arr2
print(result)

# Output:

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# In this example, arr1 (shape (3,)) and arr2 (shape (3, 1)) are broadcasted to the shape (3, 3), allowing the addition to occur.

# How They Contribute to Efficient Array Operations

# - Performance: Both vectorization and broadcasting eliminate the need for explicit loops, making operations much faster.
# - Memory Efficiency: They avoid unnecessary data duplication, saving memory.
# - Code Simplicity: They simplify the code, making it easier to read and maintain.

# Overall, these concepts help in making numerical computations with large datasets efficient and quick in NumPy.

#Practical Questions:

##1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np
arr1 = np.random.randint(1,101,(3,3))
print(arr1)
interchanged = arr1.T
print(interchanged)

[[14 65 52]
 [62 51 99]
 [71  7 71]]
[[14 62 71]
 [65 51  7]
 [52 99 71]]


##2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
import numpy as np
arr = np.array([12,45,8,63,4,7,26,32,15,5])
print(arr)
arr1 = arr.reshape(2,5)
print(arr1)
arr2 = arr.reshape(5,2)
print(arr2)

[12 45  8 63  4  7 26 32 15  5]
[[12 45  8 63  4]
 [ 7 26 32 15  5]]
[[12 45]
 [ 8 63]
 [ 4  7]
 [26 32]
 [15  5]]


##3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


In [ ]:
import numpy as np

arr = np.random.randint(1,100,(4,4)).astype(float)
print(arr)
arr1 = np.pad(arr, pad_width = 1, mode = 'constant', constant_values = 0)
print(arr1)

[[71. 18. 85. 50.]
 [18.  4. 48. 76.]
 [73. 77. 26. 19.]
 [ 4. 56. 45. 31.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0. 71. 18. 85. 50.  0.]
 [ 0. 18.  4. 48. 76.  0.]
 [ 0. 73. 77. 26. 19.  0.]
 [ 0.  4. 56. 45. 31.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


##4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.


In [ ]:
import numpy as np

arr = np.array(range(10,61,5))
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


##5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [3]:
import numpy as np
arr = np.array(['python','numpy','pandas'])
print(arr)
upper = np.char.upper(arr)
print(upper)
lower = np.char.lower(upper)
print(lower)
title = np.char.title(arr)
print(title)

['python' 'numpy' 'pandas']
['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


##6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
import numpy as np
arr = np.array(['python','numpy','pandas'])
print(arr)
spaced = np.char.join(' ', arr)
print(spaced)

['python' 'numpy' 'pandas']
['p y t h o n' 'n u m p y' 'p a n d a s']


##7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [2]:
import numpy as np

arr1 = np.array([[27,35,16],[3,54,12]])
arr2 = np.array([[6,5,8],[3,4,6]])
addition = arr1 + arr2
print(addition)
subtraction = arr1 - arr2
print(subtraction)
multiplication = arr1*arr2
print(multiplication)
division = arr1/arr2
print(division)

[[33 40 24]
 [ 6 58 18]]
[[21 30  8]
 [ 0 50  6]]
[[162 175 128]
 [  9 216  72]]
[[ 4.5  7.   2. ]
 [ 1.  13.5  2. ]]


##8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [4]:
import numpy as np
arr = np.eye(5)
print(f'identity matrix: {arr}')
diagonal = np.diagonal(arr)
print(f'diagonal elements: {diagonal}')

identity matrix: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
diagonal elements: [1. 1. 1. 1. 1.]


##9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [8]:
import numpy as np
import math
arr = np.random.randint(0,1001,100)
print(arr)

def is_prime(n):
    """Check if a number is prime."""
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False

    for i in range(5, int(math.sqrt(n)) + 1, 6):
        if n % i == 0 or n % (i + 2) == 0:
            return False
    return True

prime_numbers = [num for num in arr if is_prime(num)]

print("\nPrime Numbers in the Array:")
print(prime_numbers)


[808 522 186 664 270  98  34 316 159 107 386 420 469  37 126 414 982 907
 344 706 205 812 335 283 379 330 958 854 687 895 185 210 350 189 918 778
  54 520 515 172 509 491 484 476 677 299 676 283 719 307 606 914 842  69
 636 262  38 802 644 696  58 468 571  78   8 622 120 124 598 538  41 577
  75 147 537 496 153 994 226 827  57 726  16 667 653 125  41  74 781 350
 370 948 932 935  44 725 339 756  43 300]

Prime Numbers in the Array:
[107, 37, 907, 283, 379, 509, 491, 677, 283, 719, 307, 571, 41, 577, 827, 653, 41, 43]


##10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [13]:
import numpy as np

daily_temp = np.random.uniform(25,38,30)
print(f'Daily temperature of a month: {daily_temp}')

weekly_avg = [
    np.mean(daily_temp[0:7]),
    np.mean(daily_temp[7:14]),
    np.mean(daily_temp[14:21]),
    np.mean(daily_temp[21:])
]

for i, avg in enumerate(weekly_avg, 1):
  print(f'Week-{i}:{avg:.2f}°C')

Daily temperature of a month: [25.6947205  27.12357713 33.85419014 32.92273192 34.49624008 32.46739269
 26.12103252 33.96971111 33.62622148 28.86874308 36.91721364 32.26514145
 26.82504315 28.43632422 27.81424776 36.73431576 29.2475378  36.06777035
 34.03353189 33.56421591 28.17508356 29.80074914 32.26420976 37.30961503
 34.3173072  28.40542416 31.6511054  28.18175891 31.83724162 35.74836418]
Week-1:30.38°C
Week-2:31.56°C
Week-3:32.23°C
Week-4:32.17°C
